# Generated by Django 2.0.7 on 2018-08-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_auto_20180826_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subchapter',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='subchapter',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
